name: "Get Last.fm data"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - name: Install
        run: yarn

      - name: Generate data and top tags
        env:
            LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
            LASTFM_API_USERNAME: ${{ secrets.LASTFM_API_USERNAME }}
        run: yarn start

      - name: Push to repo
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update data"
            git push